### ISSUE TITLE
Python 3 is not supported

### ISSUE THREAD

**Issue by ignatenkobrain** [gnome-keysign/gnome-keysign#3]
### E: 29, 0: Unable to import 'scan_barcode' (import-error)
```python
from scan_barcode import BarcodeReaderGTK, ScalingImage
```
should use relative import `from .scan_barcode import ...`

and so on..

**Comment by ignatenkobrain** [comment]
keysign/KeysPage.py:
```diff
-from __init__ import __version__
+from . import __version__
```

keysign/SignPages.py:
```diff
-from compat import gtkbutton
-from scan_barcode import BarcodeReaderGTK, ScalingImage
+from .compat import gtkbutton
+from .scan_barcode import BarcodeReaderGTK, ScalingImage
```

keysign/gtkexcepthook.py:
```diff
-        trace.write(''.join(['    ' + x.replace('\t', '  ') for x in filter(lambda a: a.strip(), context)]))
+        trace.write(''.join(['    ' + x.replace('\t', '  ') for x in [a for a in context if a.strip()]]))
```

**Comment by ignatenkobrain** [comment]
```diff
-from urlparse import urlparse, parse_qs, ParseResult
+try:
+    from urlparse import urlparse, parse_qs, ParseResult
+except ImportError:
+    from urllib.parse import urlparse, parse_qs, ParseResult
```

Although if you use `six` (#4), then
```python
import six
from six.moves.urllib_parse import urlparse, parse_qs, ParseResult
```

**Comment by muelli** [comment]
cool, thanks for your input. It's certainly an issue we need to tackle.

The KeysPage and SignPage modules will be obsoleted very soon now™.  The "glade" branch already discards their use.

The gtkexcepthook should have been fixed by c6bf123a8d4b9d5d0026b45acb1599cfa43f9aad and the urlparse in f217ecae92366b00a2263a4e3f580524e1ec2f1a.

I hope that that will cut it.  Let's keep this open for now until the commits mentioned above are merged. I intend to merge the gtksink branch first and then propose the glade branch for a merge. Then, those commits should have hit master.

Please report back if that doesn't make it python3 compatible.

Note that Debian/Ubuntu currently don't ship a python3 version of Avahi https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853239 but it can be worked by doing something like `sudo ln -s  /usr/lib/python{2.7,3}/dist-packages/avahi`.

**Comment by ignatenkobrain** [comment]
@muelli Thanks!

P.S. why would I care about ubuntu? :-P

**Comment by muelli** [comment]
As it turns out, there are many more issues and help is appreciated.

One thing is a bug in [python3-cairo](https://bugs.freedesktop.org/show_bug.cgi?id=99855) ([Ubuntu bug](https://bugs.launchpad.net/ubuntu/+source/py3cairo/+bug/1330228)) which makes the current QRcode widget not compatible with python3.  Note to future self: cairocffi does not cut it because of the integration with gtk, i.e. we want to use the CairoContext we get in `do_draw` and it won't accept the cairocffi SurfacePattern.
There is [a "pure cairo" based approach](https://github.com/kabab/qr-cairo/blob/master/src/qr_image.cc#L28) which is probably worth porting to Python.

**Comment by ignatenkobrain** [comment]
@muelli why don't we use cairo via gobject introspection?

**Comment by muelli** [comment]
good point. I should have mentioned that.  The gi version is mostly useless, because cairo is not a gobject-based library. So it doesn't expose anything useful. Especially not the cairo stuff we are using, e.g. `FILTER_NEAREST` or `SurfacePattern`.

**Comment by muelli** [comment]
FTR: pycairo has been forked and there is a 1.11.0 release:  https://github.com/pygobject/pycairo/releases/tag/v1.11.0  That should have implemented the necessary function via https://github.com/pygobject/pycairo/commit/a158d9a658a7c9fee84e1c1fd3aee5aa71383884

**Comment by muelli** [comment]
https://github.com/gnome-keysign/gnome-keysign/pull/12 should remove incompatibilities on our end.
Our dependencies still suffer from python3 incompatibility.  Although apart from the already mentioned avahi and cairo, I see qrcode and requests both of which should be fine. Of course, we also have our gpg library but with the switch to gpgme we should be good.

**Comment by muelli** [comment]
I've just merged Python3 compatibility.  I think it works for me with Python 3.5 and gpgme 1.8. @RyuzakiKK  reported failures in the tests with Python 3.6 and gpgme 1.9. Can you paste the errors here so that someone can investigate further?  Once these issues are fixes, I guess we're good for closing this bug :)

**Comment by RyuzakiKK** [comment]
This is the error I get running the nose tests
https://gist.github.com/RyuzakiKK/98b12560d2d49e6b7e1d2b87290ba955

**Comment by muelli** [comment]
the errors should not appear any more. They were not python3 related, anyway.
I think we're good for Python3 support now, but I couldn't test yet, because Ubuntu lacks at least Avahi.
I'm inclined to close this issue and wait for specific reports about Python3 incompatibilities.

**Comment by RyuzakiKK** [comment]
Yeap, from my tests on Arch now Python 3 should works as expected.

**Comment by muelli** [comment]
k. Let's assume it works with Python 3. It's a bug if it doesn't. Please file a bug then.
