### ISSUE TITLE
Add a Flatpak package

### ISSUE THREAD

**Issue by purpleidea** [gnome-keysign/gnome-keysign#32]
This isn't in many (or any?) of the well-known distros. Maybe you could provide a flatpak package?

Thanks!

**Comment by purpleidea** [comment]
(and put it on flathub.org)

**Comment by muelli** [comment]
yep, we're working on it as we speak.

We have a flatpaked version here: https://muelli.cryptobitch.de/tmp/2017-01-29-keysign.flatpakref
It's a bit old though and we're building a newer version right now. @RyuzakiKK  is fighting dependency build failures atm.

Reg. Flathub, we will aim for having that as soon as we're able to build and use the app properly in the sandbox. With the (not so) recent addition of the Email-Portal and fixes in the gpg-agent, we should be able to run much more nicely than before.

Reg. packages for Distros: there are packages for Arch, OpenSuSE, Debian, and Ubuntu. I think @ignatenkobrain started to look into packaging it for Fedora, but was discouraged by the dependencies. The situation has gotten much better since, so it might be worth another shot.

We're also taking patches! ;-)

**Comment by muelli** [comment]
allora.
We're having a fully working flatpak version now :)

It's time for a release and then we're pursuing Flathub.

If you want to test the current version, you're invited to give it a try with the link mentioned above.

**Comment by muelli** [comment]
We are on Flathub now :)
https://flathub.org/apps/details/org.gnome.Keysign

If anybody is interested in nightly or beta builds, let me know.
