### ISSUE TITLE
what does the internet button do?

### ISSUE THREAD

**Issue by anarcat** [gnome-keysign/gnome-keysign#80]
There's an interesting button in the GUI labeled "internet" with some plug icon. I have absolutely no idea what it does. :) A mouse over doesn't give me any more details.

Can I turn off the entire internet with it? That would be cool. ;)

**Comment by anarcat** [comment]
and sorry for the flood of bug reports and feature requests, I hope it's useful...

**Comment by muelli** [comment]
your reports are amazing! Thanks a lot.

We discussed whether we switch the Internet off but then decided against it as it limits the supply of cute kitten pictures ;-)

It's a relatively new feature that we still need to decide how to integrate best. The feature uses the Internet as a transport rather than the local network. This is useful if your network does not allow peers to communicate, which may WiFis do these days :(
I felt, however, that using the Internet by default would be a bit too much, so it requires the user's consent with that click. We have obviously not yet reached the best way of expressing that intention.

I'm wondering though, whether we should just attempt to use the wormhole transport by default (in addition to the other transports). Then we would not necessarily need that input element which makes the app a little nicer to use.
Do you think users expect the app to rather preserve their privacy by not connecting to the Internet or rather to work even in tough networking conditions?  Would we disappoint the user more by connecting to the Internet by default or by having a non-functional app?

**Comment by anarcat** [comment]
> I'm wondering though, whether we should just attempt to use the wormhole transport by default (in addition to the other transports). Then we would not necessarily need that input element which makes the app a little nicer to use.
>
> Do you think users expect the app to rather preserve their privacy by not connecting to the Internet or rather to work even in tough networking conditions? Would we disappoint the user more by connecting to the Internet by default or by having a non-functional app?

Well, I'm not sure what the button does, really... The "security code" (presumably for magic-wormhole?) shows up in the "receive" dialog whether the button is pressed or not here.

Also, the button disappears in that window, I think it would be better if it would stick around to where it's actually relevant.

I think it's to be expected a program like gnome-keysign connects to the internet. It would be great if people would know what will happen before it does and what the implications are, but then it's hard to carry the implications of that simply in a UI.

Network failures are bad, for sure, but maybe "the internet" could be tried when failures occur, as a fallback that would require confirmation?

I really don't know what i'm talking about here, to be honest... ;)

**Comment by RyuzakiKK** [comment]
The security code is what you need to type in the receiver end for establish a connection (or you can scan the qr code).
With the internet button disabled you will get a security code that is exactly the fingerprint of your key.
And in this mode only Avahi and Bluetooth (if available) will be used.

On the opposite, if you select the internet button you'll see that the security code will be different, because it will be in the form of: number-word-anotherword
In this mode all the available transfer methods will be used: Avahi, Bluetooth and Wormhole.

With the internet option the required "security codes" for Bluetooth and Avahi will be embedded only in the qrcode, because we thought that the manual typing was only a fallback option and also because we can't show a 50 characters string and expect the users to transcribe it every time they want to transfer a key.

Maybe a popover could be useful? So when you place your mouse over "internet" a message along the line of "Enable or disable the key transfer using your Internet connection" would appear?

**Comment by muelli** [comment]
This is hopefully addressed by 4137f37b0a0e9a4e12e62eeb25643f35a49593c0.
